# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-19 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_and_ninjas', '0002_remove_ninja_dojo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninja',
            name='dojo',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='ninjas', to='dojo_and_ninjas.Dojo'),
            preserve_default=False,
        ),
    ]
