# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-19 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_and_ninjas', '0003_ninja_dojo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninja',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
