# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-19 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_and_ninjas', '0004_ninja_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ninja',
            name='description',
        ),
        migrations.AddField(
            model_name='dojo',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
